#!/bin/bash
set -e

if [ -z $ARCHER_PLATFORM ]; then
    echo "ARCHER_PLATFORM environment variable not set"
    exit 1
fi

if [ -z $ARCHER_VERSION ]; then
    echo "ARCHER_VERSION environment variable not set"
    exit 1
fi

while [[ $# -gt 0 ]]; do
    aws s3 cp $1 \
        s3://swiftinit/archer/$ARCHER_VERSION/$ARCHER_PLATFORM/$1 \
        --content-encoding gzip \
        --content-type application/gzip
    shift
done
