name: package

on:
    workflow_dispatch:
    #   We build semver tags, and the master branch.
    push:
        branches: [ master ]
        tags:
            -   '[0-9]+.[0-9]+.[0-9]+'

jobs:
    macos:
        runs-on: macos-15
        name: macOS
        steps:
            -   name: Setup AWS CLI
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build Archer
                run: |
                    swift --version
                    swift build -c release --product archer
                    tar -czf archer.tar.gz -C .build/release archer

            -   name: Upload products
                env:
                    ARCHER_PLATFORM: "${{ runner.os }}-${{ runner.arch }}"
                    ARCHER_VERSION: ${{ github.head_ref || github.ref_name }}

                run: Scripts/Deploy archer.tar.gz

    linux:
        strategy:
            matrix:
                os:
                    -   codename: jammy
                        version: Ubuntu-22.04
                        display: Ubuntu 22.04

                    -   codename: noble
                        version: Ubuntu-24.04
                        display: Ubuntu 24.04
                arch:
                    -   id: aarch64
                        name: ARM64

                    -   id: x86_64
                        name: X64

        runs-on: ubuntu-24.04
        name: "${{ matrix.os.display }} (${{ matrix.arch.id }})"
        steps:
            -   name: Setup AWS CLI
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build Archer
                run: |
                    Scripts/BuildForBinaryDistribution ${{ matrix.arch.id }} \
                        --os ${{ matrix.os.codename }} \
                    tar -czf archer.tar.gz -C .build.${{ matrix.arch.id }} archer

            -   name: Upload products
                env:
                    ARCHER_PLATFORM: "${{ matrix.os.version }}-${{ matrix.arch.name }}"
                    ARCHER_VERSION: ${{ github.head_ref || github.ref_name }}

                run: Scripts/Deploy archer.tar.gz
